spring:
  influxdb:
    url: http://localhost:8087
    username: esthesisTest
    password: esthesis
    database: esthesis
    retention-policy: autogen
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 10