["Weather_CurrentCloudiness"], -->int
["Weather_CurrentCondition"], -->
["Weather_CurrentHumidity"],
["Weather_CurrentPressure"],
["Weather_CurrentRainVolume"],
["Weather_CurrentSnowVolume"],
["Weather_CurrentTemperature"],
["Weather_CurrentWindDirection"],
["Weather_CurrentWindSpeed"],
["Weather_HourlyForecast03Cloudiness"],
["Weather_HourlyForecast03Humidity"],
["Weather_HourlyForecast03Pressure"],
["Weather_HourlyForecast03Temperature"],
["Weather_HourlyForecast03Timestamp"],
["Weather_HourlyForecast03WindDirection"],
["Weather_HourlyForecast03WindSpeed"],