package com.eurodyn.beneffice.influxDB.model;

import org.influxdb.annotation.Column;

public class BenefficeInflux {

  @Column(name = "Gas_Value")
  private String Gas_Value;
  @Column(name = "Sunrise_Time")
  private String Sunrise_Time;
  @Column(name = "Sunset_Time")
  private String Sunset_Time;
  @Column(name = "Temperature_Indoor")
  private String Temperature_Indoor;
  @Column(name = "Verbund_Watt")
  private String Verbund_Watt;
  @Column(name = "Verbund_Watt_number")
  private String Verbund_Watt_number;
  @Column(name = "Weather_CurrentCloudiness")
  private String Weather_CurrentCloudiness;
  @Column(name = "Weather_CurrentCondition")
  private String Weather_CurrentCondition;
  @Column(name = "Weather_CurrentHumidity")
  private String Weather_CurrentHumidity;
  @Column(name = "Weather_CurrentPressure")
  private String Weather_CurrentPressure;
  @Column(name = "Weather_CurrentRainVolume")
  private String Weather_CurrentRainVolume;
  @Column(name = "Weather_CurrentSnowVolume")
  private String Weather_CurrentSnowVolume;
  @Column(name = "Weather_CurrentTemperature")
  private String Weather_CurrentTemperature;
  @Column(name = "Weather_CurrentWindDirection")
  private String Weather_CurrentWindDirection;
  @Column(name = "Weather_CurrentWindSpeed")
  private String Weather_CurrentWindSpeed;
  @Column(name = "Weather_HourlyForecast03Cloudiness")
  private String Weather_HourlyForecast03Cloudiness;
  @Column(name = "Weather_HourlyForecast03Humidity")
  private String Weather_HourlyForecast03Humidity;
  @Column(name = "Weather_HourlyForecast03Pressure")
  private String Weather_HourlyForecast03Pressure;
  @Column(name = "Weather_HourlyForecast03Temperature")
  private String Weather_HourlyForecast03Temperature;
  @Column(name = "Weather_HourlyForecast03Timestamp")
  private String Weather_HourlyForecast03Timestamp;
  @Column(name = "Weather_HourlyForecast03WindDirection")
  private String Weather_HourlyForecast03WindDirection;
  @Column(name = "Weather_HourlyForecast03WindSpeed")
  private String Weather_HourlyForecast03WindSpeed;
  @Column(name = "Weather_HourlyForecast06Cloudiness")
  private String Weather_HourlyForecast06Cloudiness;
  @Column(name = "Weather_HourlyForecast06Humidity")
  private String Weather_HourlyForecast06Humidity;
  @Column(name = "Weather_HourlyForecast06Pressure")
  private String Weather_HourlyForecast06Pressure;
  @Column(name = "Weather_HourlyForecast06Temperature")
  private String Weather_HourlyForecast06Temperature;
  @Column(name = "Weather_HourlyForecast06Timestamp")
  private String Weather_HourlyForecast06Timestamp;
  @Column(name = "Weather_HourlyForecast06WindDirection")
  private String Weather_HourlyForecast06WindDirection;
  @Column(name = "Weather_HourlyForecast06WindSpeed")
  private String Weather_HourlyForecast06WindSpeed;
  @Column(name = "Weather_HourlyForecast09Cloudiness")
  private String Weather_HourlyForecast09Cloudiness;
  @Column(name = "Weather_HourlyForecast09Humidity")
  private String Weather_HourlyForecast09Humidity;
  @Column(name = "Weather_HourlyForecast09Pressure")
  private String Weather_HourlyForecast09Pressure;
  @Column(name = "Weather_HourlyForecast09Temperature")
  private String Weather_HourlyForecast09Temperature;
  @Column(name = "Weather_HourlyForecast09Timestamp")
  private String Weather_HourlyForecast09Timestamp;
  @Column(name = "Weather_HourlyForecast09WindDirection")
  private String Weather_HourlyForecast09WindDirection;
  @Column(name = "Weather_HourlyForecast09WindSpeed")
  private String Weather_HourlyForecast09WindSpeed;
  @Column(name = "Weather_HourlyForecast12Cloudiness")
  private String Weather_HourlyForecast12Cloudiness;
  @Column(name = "Weather_HourlyForecast12Humidity")
  private String Weather_HourlyForecast12Humidity;
  @Column(name = "Weather_HourlyForecast12Pressure")
  private String Weather_HourlyForecast12Pressure;
  @Column(name = "Weather_HourlyForecast12Temperature")
  private String Weather_HourlyForecast12Temperature;
  @Column(name = "Weather_HourlyForecast12Timestamp")
  private String Weather_HourlyForecast12Timestamp;
  @Column(name = "Weather_HourlyForecast12WindDirection")
  private String Weather_HourlyForecast12WindDirection;
  @Column(name = "Weather_HourlyForecast12WindSpeed")
  private String Weather_HourlyForecast12WindSpeed;
  @Column(name = "Weather_HourlyForecast15Cloudiness")
  private String Weather_HourlyForecast15Cloudiness;
  @Column(name = "Weather_HourlyForecast15Humidity")
  private String Weather_HourlyForecast15Humidity;
  @Column(name = "Weather_HourlyForecast15Pressure")
  private String Weather_HourlyForecast15Pressure;
  @Column(name = "Weather_HourlyForecast15Temperature")
  private String Weather_HourlyForecast15Temperature;
  @Column(name = "Weather_HourlyForecast15Timestamp")
  private String Weather_HourlyForecast15Timestamp;
  @Column(name = "Weather_HourlyForecast15WindDirection")
  private String Weather_HourlyForecast15WindDirection;
  @Column(name = "Weather_HourlyForecast15WindSpeed")
  private String Weather_HourlyForecast15WindSpeed;
  @Column(name = "Weather_HourlyForecast18Cloudiness")
  private String Weather_HourlyForecast18Cloudiness;
  @Column(name = "Weather_HourlyForecast18Humidity")
  private String Weather_HourlyForecast18Humidity;
  @Column(name = "Weather_HourlyForecast18Pressure")
  private String Weather_HourlyForecast18Pressure;
  @Column(name = "Weather_HourlyForecast18Temperature")
  private String Weather_HourlyForecast18Temperature;
  @Column(name = "Weather_HourlyForecast18Timestamp")
  private String Weather_HourlyForecast18Timestamp;
  @Column(name = "Weather_HourlyForecast18WindDirection")
  private String Weather_HourlyForecast18WindDirection;
  @Column(name = "Weather_HourlyForecast18WindSpeed")
  private String Weather_HourlyForecast18WindSpeed;
  @Column(name = "Weather_HourlyForecast21Cloudiness")
  private String Weather_HourlyForecast21Cloudiness;
  @Column(name = "Weather_HourlyForecast21Humidity")
  private String Weather_HourlyForecast21Humidity;
  @Column(name = "Weather_HourlyForecast21Pressure")
  private String Weather_HourlyForecast21Pressure;
  @Column(name = "Weather_HourlyForecast21Temperature")
  private String Weather_HourlyForecast21Temperature;
  @Column(name = "Weather_HourlyForecast21Timestamp")
  private String Weather_HourlyForecast21Timestamp;
  @Column(name = "Weather_HourlyForecast21WindDirection")
  private String Weather_HourlyForecast21WindDirection;
  @Column(name = "Weather_HourlyForecast21WindSpeed")
  private String Weather_HourlyForecast21WindSpeed;
  @Column(name = "Weather_HourlyForecast24Cloudiness")
  private String Weather_HourlyForecast24Cloudiness;
  @Column(name = "Weather_HourlyForecast24Humidity")
  private String Weather_HourlyForecast24Humidity;
  @Column(name = "Weather_HourlyForecast24Pressure")
  private String Weather_HourlyForecast24Pressure;
  @Column(name = "Weather_HourlyForecast24Temperature")
  private String Weather_HourlyForecast24Temperature;
  @Column(name = "Weather_HourlyForecast24Timestamp")
  private String Weather_HourlyForecast24Timestamp;
  @Column(name = "Weather_HourlyForecast24WindDirection")
  private String Weather_HourlyForecast24WindDirection;
  @Column(name = "Weather_HourlyForecast24WindSpeed")
  private String Weather_HourlyForecast24WindSpeed;
  @Column(name = "Weather_HourlyForecast27Cloudiness")
  private String Weather_HourlyForecast27Cloudiness;
  @Column(name = "Weather_HourlyForecast27Humidity")
  private String Weather_HourlyForecast27Humidity;
  @Column(name = "Weather_HourlyForecast27Pressure")
  private String Weather_HourlyForecast27Pressure;
  @Column(name = "Weather_HourlyForecast27Temperature")
  private String Weather_HourlyForecast27Temperature;
  @Column(name = "Weather_HourlyForecast27Timestamp")
  private String Weather_HourlyForecast27Timestamp;
  @Column(name = "Weather_HourlyForecast27WindDirection")
  private String Weather_HourlyForecast27WindDirection;
  @Column(name = "Weather_HourlyForecast27WindSpeed")
  private String Weather_HourlyForecast27WindSpeed;
  @Column(name = "Weather_HourlyForecast30Cloudiness")
  private String Weather_HourlyForecast30Cloudiness;
  @Column(name = "Weather_HourlyForecast30Humidity")
  private String Weather_HourlyForecast30Humidity;
  @Column(name = "Weather_HourlyForecast30Pressure")
  private String Weather_HourlyForecast30Pressure;
  @Column(name = "Weather_HourlyForecast30Temperature")
  private String Weather_HourlyForecast30Temperature;
  @Column(name = "Weather_HourlyForecast30Timestamp")
  private String Weather_HourlyForecast30Timestamp;
  @Column(name = "Weather_HourlyForecast30WindDirection")
  private String Weather_HourlyForecast30WindDirection;
  @Column(name = "Weather_HourlyForecast30WindSpeed")
  private String Weather_HourlyForecast30WindSpeed;
  @Column(name = "Weather_HourlyForecast33Cloudiness")
  private String Weather_HourlyForecast33Cloudiness;
  @Column(name = "Weather_HourlyForecast33Humidity")
  private String Weather_HourlyForecast33Humidity;
  @Column(name = "Weather_HourlyForecast33Pressure")
  private String Weather_HourlyForecast33Pressure;
  @Column(name = "Weather_HourlyForecast33Temperature")
  private String Weather_HourlyForecast33Temperature;
  @Column(name = "Weather_HourlyForecast33Timestamp")
  private String Weather_HourlyForecast33Timestamp;
  @Column(name = "Weather_HourlyForecast33WindDirection")
  private String Weather_HourlyForecast33WindDirection;
  @Column(name = "Weather_HourlyForecast33WindSpeed")
  private String Weather_HourlyForecast33WindSpeed;
  @Column(name = "Weather_HourlyForecast36Cloudiness")
  private String Weather_HourlyForecast36Cloudiness;
  @Column(name = "Weather_HourlyForecast36Humidity")
  private String Weather_HourlyForecast36Humidity;
  @Column(name = "Weather_HourlyForecast36Pressure")
  private String Weather_HourlyForecast36Pressure;
  @Column(name = "Weather_HourlyForecast36Temperature")
  private String Weather_HourlyForecast36Temperature;
  @Column(name = "Weather_HourlyForecast36Timestamp")
  private String Weather_HourlyForecast36Timestamp;
  @Column(name = "Weather_HourlyForecast36WindDirection")
  private String Weather_HourlyForecast36WindDirection;
  @Column(name = "Weather_HourlyForecast36WindSpeed")
  private String Weather_HourlyForecast36WindSpeed;
  @Column(name = "Weather_HourlyForecast39Cloudiness")
  private String Weather_HourlyForecast39Cloudiness;
  @Column(name = "Weather_HourlyForecast39Humidity")
  private String Weather_HourlyForecast39Humidity;
  @Column(name = "Weather_HourlyForecast39Pressure")
  private String Weather_HourlyForecast39Pressure;
  @Column(name = "Weather_HourlyForecast39Temperature")
  private String Weather_HourlyForecast39Temperature;
  @Column(name = "Weather_HourlyForecast39Timestamp")
  private String Weather_HourlyForecast39Timestamp;
  @Column(name = "Weather_HourlyForecast39WindDirection")
  private String Weather_HourlyForecast39WindDirection;
  @Column(name = "Weather_HourlyForecast39WindSpeed")
  private String Weather_HourlyForecast39WindSpeed;
  @Column(name = "Weather_HourlyForecast42Cloudiness")
  private String Weather_HourlyForecast42Cloudiness;
  @Column(name = "Weather_HourlyForecast42Humidity")
  private String Weather_HourlyForecast42Humidity;
  @Column(name = "Weather_HourlyForecast42Pressure")
  private String Weather_HourlyForecast42Pressure;
  @Column(name = "Weather_HourlyForecast42Temperature")
  private String Weather_HourlyForecast42Temperature;
  @Column(name = "Weather_HourlyForecast42Timestamp")
  private String Weather_HourlyForecast42Timestamp;
  @Column(name = "Weather_HourlyForecast42WindDirection")
  private String Weather_HourlyForecast42WindDirection;
  @Column(name = "Weather_HourlyForecast42WindSpeed")
  private String Weather_HourlyForecast42WindSpeed;
  @Column(name = "Weather_HourlyForecast45Cloudiness")
  private String Weather_HourlyForecast45Cloudiness;
  @Column(name = "Weather_HourlyForecast45Humidity")
  private String Weather_HourlyForecast45Humidity;
  @Column(name = "Weather_HourlyForecast45Pressure")
  private String Weather_HourlyForecast45Pressure;
  @Column(name = "Weather_HourlyForecast45Temperature")
  private String Weather_HourlyForecast45Temperature;
  @Column(name = "Weather_HourlyForecast45Timestamp")
  private String Weather_HourlyForecast45Timestamp;
  @Column(name = "Weather_HourlyForecast45WindDirection")
  private String Weather_HourlyForecast45WindDirection;
  @Column(name = "Weather_HourlyForecast45WindSpeed")
  private String Weather_HourlyForecast45WindSpeed;
  @Column(name = "Weather_HourlyForecast48Cloudiness")
  private String Weather_HourlyForecast48Cloudiness;
  @Column(name = "Weather_HourlyForecast48Humidity")
  private String Weather_HourlyForecast48Humidity;
  @Column(name = "Weather_HourlyForecast48Pressure")
  private String Weather_HourlyForecast48Pressure;
  @Column(name = "Weather_HourlyForecast48Temperature")
  private String Weather_HourlyForecast48Temperature;
  @Column(name = "Weather_HourlyForecast48Timestamp")
  private String Weather_HourlyForecast48Timestamp;
  @Column(name = "Weather_HourlyForecast48WindDirection")
  private String Weather_HourlyForecast48WindDirection;
  @Column(name = "Weather_HourlyForecast48WindSpeed")
  private String Weather_HourlyForecast48WindSpeed;
  @Column(name = "Weather_LastMeasurement")
  private String Weather_LastMeasurement;
  @Column(name = "Weather_StationId")
  private String Weather_StationId;
  @Column(name = "geolocation")
  private String geolocation;
  @Column(name = "health")
  private String health;
  @Column(name = "temp_sensor")
  private String temp_sensor;
  @Column(name = "user_email")
  private String user_email;
  @Column(name = "vpm_macid")
  private String vpm_macid;
}